# base node image
# FROM node:16-bullseye-slim as base
FROM node:16-bullseye as base

# set for base and all layer that inherit from it
ENV NODE_ENV production

# Install openssl for Prisma
RUN apt-get update && apt-get install -y openssl

# Install all node_modules for letterpress workspace and build package
FROM base as letterpress-build

WORKDIR /opt/packages/letterpress
ADD ./packages/letterpress/ ./
RUN npm install --production=false --ignore-scripts
# TODO: Build parcel watcher until this is fixed: https://github.com/parcel-bundler/watcher/issues/101 
RUN cd /opt/packages/letterpress/node_modules/@parcel/watcher && npm run install
# WORKDIR /opt/packages/letterpress
RUN npm run parcel:build
RUN ls -lash /opt/packages/letterpress/dist && sleep 20

# Install all node_modules, including dev dependencies
FROM base as newspaper-dev-deps

WORKDIR /opt/myapp
ADD ./newspaper/package.json ./newspaper/package-lock.json ./newspaper/.npmrc ./
RUN npm install --production=false

# Setup production node_modules
FROM base as production-deps

WORKDIR /opt/myapp
COPY --from=newspaper-dev-deps /opt/myapp/node_modules /opt/myapp/node_modules
ADD ./newspaper/package.json ./newspaper/.npmrc ./
RUN npm prune --production

FROM base as build

WORKDIR /opt/packages/letterpress
ADD ./packages/letterpress/package.json ./
COPY --from=letterpress-build /opt/packages/letterpress/dist /opt/packages/letterpress/dist 
COPY --from=letterpress-build /opt/packages/letterpress/node_modules /opt/packages/letterpress/node_modules

WORKDIR /opt/myapp
COPY --from=newspaper-dev-deps /opt/myapp/node_modules /opt/myapp/node_modules

ADD ./newspaper/prisma .
RUN npx prisma generate

ADD ./newspaper .
RUN npm i --production=false
RUN npm run hello:esbuild
RUN npm run build

# Finally, build the production image with minimal footprint
FROM base

WORKDIR /opt/packages/letterpress
ADD ./packages/letterpress/package.json ./
COPY --from=letterpress-build /opt/packages/letterpress/dist /opt/packages/letterpress/dist 

WORKDIR /opt/myapp

# COPY --from=production-deps /opt/myapp/node_modules /opt/myapp/node_modules
COPY --from=newspaper-dev-deps /opt/myapp/node_modules /opt/myapp/node_modules
COPY --from=build /opt/myapp/node_modules/.prisma /opt/myapp/node_modules/.prisma

COPY --from=build /opt/myapp/build /opt/myapp/build
COPY --from=build /opt/myapp/public /opt/myapp/public
ADD ./newspaper .
RUN npm i --production=true

CMD ["npm", "start"]
