services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      # interval: 30s
      # timeout: 20s
      # retries: 3
      interval: 5s
      timeout: 5s
      retries: 5
    hostname: minio
    # volumes:
    #   - minio:/data1

  bootstrap:
    build:
      context: ./
      dockerfile: ./packages/bootstrap/Dockerfile
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./packages/bootstrap/.env
    environment:
      - S3_INVENTORY_FOLDER=/inventory
    volumes:
      - ./inventory:/inventory

  seed:
    build:
      context: ./
      dockerfile: ./packages/prismatic/Dockerfile
    env_file:
      - ./packages/prismatic/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./inventory:/inventory

volumes:
  minio:
