version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  newspaper:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./newspaper/Dockerfile
    env_file:
      - ./newspaper/.env
    # restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    # stop_grace_period: "3s"
    init: true
    depends_on:
      - "postgres"
    ports:
      - 3000:3000
